# Generated by Django 4.1.7 on 2023-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=800)),
                ('DueDate', models.CharField(max_length=15)),
                ('AssignedEmployee', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=20)),
                ('StatusDescription', models.CharField(max_length=256)),
            ],
        ),
    ]
