# Generated by Django 4.1.7 on 2023-02-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
