# Generated by Django 4.1.7 on 2023-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_createtask_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('EmployeeId', models.CharField(max_length=50)),
                ('EmployeeDesignation', models.CharField(max_length=50)),
            ],
        ),
    ]
