# Generated by Django 4.1.7 on 2023-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
