# Generated by Django 4.1.7 on 2023-02-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_profiles_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectDescription', models.CharField(max_length=800)),
                ('ProjectDeadline', models.CharField(max_length=15)),
                ('AssignedManager', models.CharField(max_length=25)),
                ('Status', models.CharField(max_length=20)),
                ('StatusDescription', models.CharField(max_length=256)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
