# Generated by Django 4.1.7 on 2023-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
