# Generated by Django 4.1.7 on 2023-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_createbug_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
