# Generated by Django 4.1.7 on 2023-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0008_alter_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
