# Generated by Django 4.1.7 on 2023-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_rename_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
